version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_DB: staging_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: etl_sqlserver
    environment:
      SA_PASSWORD: "Sqlserver@2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  
  etl_app:
    build: .
    container_name: etl_app
    depends_on:
      - postgres
      - sqlserver

volumes:
  pgdata:
  sqlserverdata:
